apiVersion: v1
kind: Service
metadata:
  name: {{ include "activemq.fullname" . }}
  labels:
    {{- include "activemq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if not .Values.tls.enabled }}
  - name: openwire
    port: {{ .Values.service.port }}
    targetPort: openwire
    protocol: TCP
  - name: webconsole
    port: {{ .Values.service.webConsolePort }}
    targetPort: webconsole
    protocol: TCP
  {{- else }}
  - name: openwire-ssl
    port: {{ .Values.tls.sslPort }}
    targetPort: openwire-ssl
    protocol: TCP
  - name: webconsole-ssl
    port: {{ .Values.tls.webConsoleSslPort }}
    targetPort: webconsole-ssl
    protocol: TCP
  {{- end }}
  selector:
    {{- include "activemq.selectorLabels" . | nindent 4 }}